### ISSUE TITLE
앞으로 해야할 것들

### ISSUE THREAD

**Issue by sungkyulh** [WhiteHyun/smart-locker#7]
## TODO

- [x] 케이스 제작
- [x]  DB 제작
- [x] QR 코드 사용자에게 전달 방식 구현
- [x]  택배함내 물건 확인 방법 구현
- [x]  택배함 문 닫힘 확인 방법 구현
- [x]  관리용 페이지(미정)

**Comment by WhiteHyun** [comment]
# 관리용 페이지 만들 경우

1. 사물함 번호 설정
2. 고장 여부 설정
3. 문 강제 개방 설정
